<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>beb510b4-9b5a-4c29-840b-2d5df757936c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Extensions\**" />
    <Compile Remove="Middleware\**" />
    <Compile Remove="Models\Payments\**" />
    <Content Remove="Extensions\**" />
    <Content Remove="Middleware\**" />
    <Content Remove="Models\Payments\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <EmbeddedResource Remove="Middleware\**" />
    <EmbeddedResource Remove="Models\Payments\**" />
    <None Remove="Extensions\**" />
    <None Remove="Middleware\**" />
    <None Remove="Models\Payments\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AKLC.Application\AKLC.Application.csproj" />
    <ProjectReference Include="..\AKLC.Infrastructure\AKLC.Infrastructure.csproj" />
  </ItemGroup>

</Project>
